# Generated by Django 5.1.5 on 2025-01-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=250)),
                ('tipo_de_gestion', models.CharField(max_length=250)),
                ('numero_caso', models.CharField(max_length=250)),
                ('detectada_por', models.CharField(max_length=250)),
                ('causado_por_certificado_digital', models.BooleanField()),
                ('incidente_generado_por_OC', models.BooleanField()),
                ('atribuible_a', models.CharField(max_length=30)),
                ('tipo_de_falla', models.CharField(max_length=30)),
                ('detalle', models.TextField()),
                ('tipo_causa', models.CharField(max_length=30)),
                ('causa', models.TextField()),
                ('validaciones', models.TextField()),
                ('solucion', models.TextField()),
                ('responsable_gioti', models.CharField(max_length=250)),
                ('fecha_hora_inicial', models.DateTimeField(verbose_name='Fecha y Hora Inicial')),
                ('fecha_hora_final', models.DateTimeField(verbose_name='Fecha y Hora Final')),
                ('postular_amg', models.BooleanField()),
                ('gioti', models.BooleanField()),
            ],
        ),
    ]
