# Generated by Django 5.1.5 on 2025-02-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio", models.CharField(max_length=250, verbose_name="Servicio")),
                (
                    "tipo_de_gestion",
                    models.CharField(max_length=250, verbose_name="Tipo de gestion"),
                ),
                (
                    "numero_caso",
                    models.CharField(max_length=250, verbose_name="Numero de caso"),
                ),
                (
                    "detectada_por",
                    models.CharField(max_length=250, verbose_name="Detectado por"),
                ),
                (
                    "causado_por_certificado_digital",
                    models.BooleanField(
                        default=False, verbose_name="Causado por certificado digital"
                    ),
                ),
                (
                    "incidente_generado_por_OC",
                    models.BooleanField(
                        default=False, verbose_name="Incidente generado por OC"
                    ),
                ),
                (
                    "atribuible_a",
                    models.CharField(max_length=30, verbose_name="Atribuible a"),
                ),
                (
                    "tipo_de_falla",
                    models.CharField(max_length=30, verbose_name="Tipo de falla"),
                ),
                ("detalle", models.TextField(verbose_name="Detalle")),
                (
                    "tipo_causa",
                    models.CharField(max_length=30, verbose_name="Tipo_causa"),
                ),
                ("causa", models.TextField(verbose_name="Causa")),
                ("validaciones", models.TextField(verbose_name="Validaciones")),
                ("solucion", models.TextField(verbose_name="Solucion")),
                (
                    "responsable_gioti",
                    models.CharField(max_length=250, verbose_name="Responsable gioti"),
                ),
                (
                    "fecha_hora_inicial",
                    models.DateTimeField(verbose_name="Fecha y Hora Inicial"),
                ),
                (
                    "fecha_hora_final",
                    models.DateTimeField(verbose_name="Fecha y Hora Final"),
                ),
                (
                    "postular_amg",
                    models.BooleanField(default=False, verbose_name="Postular AMG"),
                ),
                ("gioti", models.BooleanField(default=False, verbose_name="GIOTI")),
            ],
            options={
                "verbose_name": "Gestion",
                "verbose_name_plural": "Gestiones",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio", models.CharField(max_length=300)),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha creacion"),
                ),
            ],
        ),
    ]
