# Generated by Django 5.1.5 on 2025-02-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestiones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestion",
            name="fecha_hora_final",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y Hora Final"
            ),
        ),
    ]
