# Generated by Django 5.1.5 on 2025-01-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha creacion')),
            ],
        ),
    ]
