# Generated by Django 5.1.5 on 2025-01-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0002_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='causado_por_certificado_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='gioti',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='incidente_generado_por_OC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='postular_amg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(max_length=300),
        ),
    ]
