# Generated by Django 5.1.5 on 2025-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestiones", "0002_alter_gestion_fecha_hora_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestion",
            name="atribuible_a",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Atribuible a"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="causa",
            field=models.TextField(blank=True, null=True, verbose_name="Causa"),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="detalle",
            field=models.TextField(blank=True, null=True, verbose_name="Detalle"),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="detectada_por",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Detectado por"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="numero_caso",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Numero de caso"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="servicio",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Servicio"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="solucion",
            field=models.TextField(blank=True, null=True, verbose_name="Solucion"),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="tipo_causa",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Tipo_causa"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="tipo_de_falla",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Tipo de falla"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="tipo_de_gestion",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Tipo de gestion"
            ),
        ),
        migrations.AlterField(
            model_name="gestion",
            name="validaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Validaciones"),
        ),
    ]
