# Generated by Django 5.1.5 on 2025-02-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mejoracgm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio", models.CharField(max_length=250, verbose_name="Servicio")),
                (
                    "herramienta_de_monitoreo",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Herramienta de monitoreo",
                    ),
                ),
                (
                    "tipo_de_mejora",
                    models.CharField(max_length=250, verbose_name="Tipo de Mejora"),
                ),
                (
                    "numero_peticion",
                    models.CharField(max_length=250, verbose_name="Número Petición"),
                ),
                (
                    "numero_wo",
                    models.CharField(max_length=250, verbose_name="Número WO"),
                ),
                ("servidor", models.CharField(max_length=500, verbose_name="Servidor")),
                ("variable", models.TextField(verbose_name="Variable de la alerta")),
                (
                    "peticion_reincidente",
                    models.CharField(
                        max_length=250, verbose_name="Petición Reincidente"
                    ),
                ),
                (
                    "peticion_anterior",
                    models.CharField(
                        max_length=250, verbose_name="N° Petición Anterior"
                    ),
                ),
                ("observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "fecha_hora_mejora",
                    models.DateTimeField(verbose_name="Fecha y Hora Mejora"),
                ),
                (
                    "area_responsable",
                    models.CharField(max_length=250, verbose_name="Área Responsable"),
                ),
                (
                    "mejora_creada_por",
                    models.CharField(max_length=250, verbose_name="Mejora Creada Por"),
                ),
                ("estado", models.CharField(max_length=250, verbose_name="Estado")),
                ("solucion", models.TextField(verbose_name="Descripción")),
                ("fecha_hora", models.DateTimeField(verbose_name="Fecha y Hora")),
            ],
        ),
    ]
