# Generated by Django 5.1.5 on 2025-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mejorascgm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mejoracgm",
            name="fecha_hora",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
