# Generated by Django 5.1.5 on 2025-02-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mejorascgm", "0002_alter_mejoracgm_fecha_hora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mejoracgm",
            options={
                "verbose_name": "Mejora CGM",
                "verbose_name_plural": "Mejoras CGM",
            },
        ),
        migrations.AlterField(
            model_name="mejoracgm",
            name="fecha_hora",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="fecha y hora de cierre de la mejora",
            ),
        ),
    ]
